### ISSUE TITLE
'strafe mode' controls

### ISSUE THREAD

**Issue by bbarski** [AryanWolf3D/Wolf4SDL#16]
Wolfenstein 3D control scheme is a little too oldschool. 
Nice to have what I'd call 'strafe mode', instead of dedicated strafe keys, so you can't really play it like you would any other FPS.
like in this fork
https://github.com/Billy2600/wolf4sdl

**Comment by AlumiuN** [comment]
This is probably outside the scope of this port; that said, I do know there's a tutorial somewhere for adding this yourself (although I can't find it currently).
