### ISSUE TITLE
Doesn’t compile under Linux

### ISSUE THREAD

**Issue by lukasfink1** [AryanWolf3D/Wolf4SDL#18]
The all-caps filenames currently prevent this from being compiled under case sensitive file systems. It seems like they should be lowercase as the filenames in Wolf4SDL.vcproj and the includes suggest it.

**Comment by AlumiuN** [comment]
My unfamiliarity with Git is giving me a little trouble with figuring out how to do this in any reasonable way; is there a way to do it without having to manually rename each file?

**Comment by KS-Presto** [comment]
Alright, all source files & folders are lowercase now.
