### ISSUE TITLE
Receiving SafeMalloc error when trying to play with SW v1.4

### ISSUE THREAD

**Issue by danielpcowen** [AryanWolf3D/Wolf4SDL#29]
Hi All,

I'm receiving a SafeMalloc error when trying to play the Wolf3d shareware version 1.4 with the latest source code download from this repository.

System: Linux Mint Cinnamon (Ubuntu 20.04); i5 6600K; 32GB RAM

Error message: SafeMalloc: Out of memory at id_ca.c: line 992

Steps to reproduce:
Clone this repository
Update version.h to remove #define of GOODTIMES and to add #define of UPLOAD
Download Wolfenstein 3D Shareware version 1.4 and copy data files into root Wolf4SDL directory. I have received the error with two separate repositories - https://archive.org/download/Wolfenstein3d/Wolfenstein3dV14sw.ZIP from https://archive.org/details/Wolfenstein3d and wolf3d-box.zip from https://www.dosgamesarchive.com/download/wolfenstein-3d/)
As Linux is case-senstiive I also have to rename the files to lowercase (have done this twice and cross-checked the names both times)
Run make in the Wolf4SDL root directory
Run wolf3d, my screens go blank for about 2 seconds and then it returns to my Linux desktop with the above error message on my terminal.

I have done a small amount of source code investigation and have found that the size of the vgahead.wl1 file in the above repositories does not seem to be large enough for the value of NUMCHUNKS that the program is attempting to read (vgahead.wl1 is 471 bytes vs 161 NUMCHUNKS x3 bytes / chunk =481 bytes), and the SafeMalloc() error appears to occur on chunk 156. However, I am definitely not an expert with the Wolf3d source code so any feedback about how to fix would be appreciated.

Kind regards,
Daniel

**Comment by KS-Presto** [comment]
Hi, thanks for the report (and sorry for the late response...), I'll look into this as soon as I can and let you know when it's fixed.

Cheers!

**Comment by KS-Presto** [comment]
Alright, I think I found the problem [here](https://github.com/AryanWolf3D/Wolf4SDL/commit/30dacd9bf1b4abd8e6c25955eaa641d74f5a62a8).

Please let me know if this fixes it for you.

**Comment by danielpcowen** [comment]
Working perfectly now thank you!

Though interestingly, it looks like the default SDL version has been shifted to SDL2, as I had to install some new SDL2 libraries in my computer in order to get the new code to compile.

Also I was wondering whether there are any resources out there to better understand what each file (and function within each file) does? I am thinking of having a go of porting Wolf3D to a different system and in order to do this I need to better understand what each part of the source code is doing.

Kind regards,
Daniel

**Comment by KS-Presto** [comment]
That's good to hear.

Huh, it should still compile for SDL 1.2 without any problems as long as the compiler knows where to look. What problems did you have exactly?

Unfortunately I don't really know of anything that does a complete breakdown of the source. You could try Fabien Sanglard's Game Engine Black Book for an overall explanation (though it deals with the DOS code). In general though, the files are something like this:

First off there's the heavily used wl_def.h, which contains common defs for pretty much everything, and version.h for version/feature control

Then there's the id_?? files:

id_ca: The caching manager, loads in all the 2D graphics, audio, and level data
id_in: Input manager, standard keyboard/mouse/controller code & event processing
id_pm: Page manager, the whole VSWAP file is read into an array here
id_sd: Sound manager, pretty self explanatory (but also a mess at the moment...)
id_us: User manager, mostly handles string inputs
id_vh/id_vl: Video manager, handles loading SDL surfaces/textures and drawing to VRAM

Then the core engine files:

wl_act1: Static objects, doors & area codes, pushwalls
wl_act2 & wl_state: Actor states and functions
wl_agent: Player state handling and statusbar updates
wl_debug: Contains the cheat codes and the new overhead map
wl_draw: The 3D renderer, contains the core raycaster and sprite projection & sorting
wl_game: The core game loop (calls the 3D environment PlayLoop), level caching and setup, demo recording & playback routines
wl_inter: Level transitions, victory screens
wl_main: The core "demo" loop (cycles through the title screens, calls the menu handler and GameLoop), save/load game and config handling
wl_menu: 'nuff said
wl_play: The 3D environment. Contains the core play loop with calls to the 3D renderer and actor state machines
wl_scale: Sprite drawing routines
wl_text: A simple text presenter with ART text chunk functions
wl_utils: A new file with some misc functions
signon: Contains two arrays of palette indexes for the startup screens for both Wolf & Spear
sodpal/wolfpal.inc: The game's palette

There are also optional features contained in wl_atmos, wl_cloudsky, wl_shade, & wl_parallax

The source is small enough that it's pretty easy to get to know everything, and a lot of the important stuff is commented. But I'll always be glad to help if you need it.
