### ISSUE TITLE
Interest in an SDL2 PR? PR for Chocolate Wolfenstein 3D in progress.

### ISSUE THREAD

**Issue by zZeck** [AryanWolf3D/Wolf4SDL#33]
[I have done this for Chocolate Wolfenstein 3D.](https://github.com/fabiensanglard/Chocolate-Wolfenstein-3D/pull/24)

I see this codebase is moving away from C++, but I can use something other than an unordered_map for input. The SDL code in here looks very similar still?

**Comment by KS-Presto** [comment]
I guess you mean porting it to SDL2? I do have this planned at some point, but if you'd like to do it then sure. I don't want the 1.2 compatibility being removed though, because some people might still want to use it. So it should be able to be compiled for both (using a #define in version.h).

**Comment by zZeck** [comment]
Yeah, porting to SDL2 is what I mean.  I'll give it a shot and keep 1.2 support.
